## Minimal repro: mixin/bind statements crash cuda: macro
##
## Crucible's toGpuAst crashes on nnkMixinStmt / nnkBindStmt.
## These are compile-time resolution hints generated by templates,
## irrelevant for GPU codegen — they should be skipped.
##
## Run:
##   cd tattletale
##   CUDA_HOME=... PATH=... nim cpp -r \
##     workspace/crucible/tests/codegen/nvrtc/test_nvrtc_mixin_bind.nim

import std/[unittest]
import workspace/crucible/src/codegen/nvrtc

# A template that uses `mixin` to bring a proc into scope
template callMixin(body: untyped): untyped =
  mixin dummyProc
  block:
    body

type
  Int*[V: static int] = object
    discard

# Use the template inside a cuda: block — this generates a mixin stmt
const kernel = cuda:
  proc kernel(C: ptr UncheckedArray[uint32]) {.global.} =
    callMixin:
      let x = Int[8]()
    C[0] = 1'u32

suite "Crucible - mixin/bind statements":
  test "template with mixin inside cuda: compiles":
    var output: array[1, uint32]
    var nv = initNvrtc(kernel)
    nv.numBlocks = 1
    nv.threadsPerBlock = 1
    nv.compile()
    nv.getPtx()
    nv.execute("kernel", output, ())
    check output[0] == 1
