# Tattletale
# Copyright (c) 2026 Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

## Test Qwen3 long residual stream invariant with intermediate value verification.
##
## This test verifies that the Nim long residual stream implementation
## produces IDENTICAL intermediate values to the HF reference.
##
## Fixtures generated by gen_3_block_long_residual.py contain ALL intermediates
## so we can verify every step of the forward pass matches.
##
## Tolerance: 1e-3 for intermediate values.
## The invariant should hold with diff=0.0 with FP32 RMSNorm.
##
## MUST NOT BE DELETED: The long residual stream invariant is:
##   At each layer boundary: output + residual == x_local
## This is proven in WIP/Spec_Residual_Patterns.md.

import
  std/memfiles,
  std/strformat,
  std/tables,
  std/os,
  std/options,
  std/importutils,
  workspace/libtorch,
  workspace/safetensors,
  workspace/safetensors/src/safetensors_libtorch,
  workspace/transformers/src/layers,
  workspace/transformers/src/layers/rope {.all.},
  workspace/transformers/src/models/qwen3 {.all.},
  workspace/libtorch_testutils

const
  FixtureDir = currentSourcePath().parentDir() / "fixtures" / "long-residual-3-block"
  ModelPath = currentSourcePath().parentDir() / "hf_models" / "Qwen3-0.6B"

proc loadFixture(layerIdx: int): Table[string, Tensor] =
  let fixturePath = FixtureDir / &"block-{layerIdx:02d}.safetensor"
  var memFile = memFiles.open(fixturePath, mode = fmRead)
  defer: close(memFile)
  let st = safetensors.load(memFile)
  result = initTable[string, Tensor]()
  for name in st.tensors.keys():
    result[name] = st.getTensorOwned(name, kCPU)

proc checkTensor(name: string, actual, expected: Tensor, tol: float): float =
  ## Check that actual and expected tensors match within tolerance.
  ## Raises exception if diff exceeds tolerance.
  ## Returns the max diff for reporting.
  let diff = (actual.to(kFloat32) - expected.to(kFloat32)).abs().max().item(float)
  if diff > tol:
    raise newException(ValueError, &"{name}: diff={diff:.6e} exceeds tolerance {tol:.1e}")
  diff

proc main() =
  runTest "Qwen3 long residual stream - intermediate verification (3 blocks)":
    proc(): bool =
      const tol = 1e-3

      let model = loadQwen3ModelRaw(ModelPath, kCPU)
      privateAccess(Qwen3Model)

      # Input tokens: "Hello, how are you?"
      let inputIds = @[9707.int64, 11, 1246, 525, 498, 30].toTensor().unsqueeze(0)

      # Embedding pass
      let x = model.embedTokens.forward(inputIds)
      var hidden = x
      var residual: Option[Tensor] = none(Tensor)

      echo "Comparing 3-block long residual stream intermediates..."
      echo "================================================================="

      for layerIdx in 0..2:
        let fixture = loadFixture(layerIdx)
        var layer = model.layers[layerIdx]

        # Set RoPE cache from fixture (HF computed values)
        layer.attn.rotary.setCache(fixture["cos"], fixture["sin"])

        echo &"Layer {layerIdx:02d}:"

        block:
          # ── Manual reimplementation of TransformerBlock.forward ──
          # This matches the forward() method in transformer.nim exactly.

          # Step 1: attn_norm.forward_with_residual(x, residual)
          let (h, r) =
            if residual.isSome():
              let res = residual.unsafeGet()
              let new_res = hidden + res
              checkTensor(&"L{layerIdx:02d}_attn_norm", layer.attnNorm.forward(new_res),
                          fixture["after_attn_norm"], tol)
              checkTensor(&"L{layerIdx:02d}_attn_res", new_res,
                          fixture["after_attn_norm_residual"], tol)
              (layer.attnNorm.forward(new_res), new_res)
            else:
              let h_norm = layer.attnNorm.forward(hidden)
              checkTensor(&"L{layerIdx:02d}_attn_norm", h_norm,
                          fixture["after_attn_norm"], tol)
              checkTensor(&"L{layerIdx:02d}_attn_res", hidden,
                          fixture["after_attn_norm_residual"], tol)
              (h_norm, hidden)

          # Step 2: attention
          let attn_out = layer.attn.forward(h)
          checkTensor(&"L{layerIdx:02d}_attn", attn_out, fixture["after_attn"], tol)

          # Step 3: mlp_norm.forward_with_residual(attn_out, r)
          let combined = attn_out + r
          checkTensor(&"L{layerIdx:02d}_mlp_res", combined,
                      fixture["after_mlp_norm_residual"], tol)
          let h2_norm = layer.mlpNorm.forward(combined)
          checkTensor(&"L{layerIdx:02d}_mlp_norm", h2_norm,
                      fixture["after_mlp_norm"], tol)

          # Step 4: mlp
          let mlp_out = layer.mlp.forward(h2_norm)
          checkTensor(&"L{layerIdx:02d}_mlp", mlp_out, fixture["mlp_out"], tol)

          # Step 5: Invariant check - mlp_out + residual == hf_layer_output
          let nimSum = mlp_out + combined
          let invDiff = checkTensor(&"L{layerIdx:02d}_invariant", nimSum,
                                    fixture["hf_layer_output"], tol)
          echo &"  invariant diff={invDiff:.2e}"

        block:
          # ── Call real TransformerBlock.forward and verify it matches ──
          layer.attn.rotary.setCache(fixture["cos"], fixture["sin"])
          let (real_out, real_res) = layer.forward(hidden, residual)

          checkTensor(&"L{layerIdx:02d}_real_out", real_out,
                      fixture["mlp_out"], tol)
          checkTensor(&"L{layerIdx:02d}_real_res", real_res,
                      fixture["after_mlp_norm_residual"], tol)
          let realSum = real_out + real_res
          let realInvDiff = checkTensor(&"L{layerIdx:02d}_real_invariant", realSum,
                                        fixture["hf_layer_output"], tol)
          echo &"  real forward invariant diff={realInvDiff:.2e}"

        # Update state for next layer using the real forward's output
        layer.attn.rotary.setCache(fixture["cos"], fixture["sin"])
        let (fwd_out, fwd_res) = layer.forward(hidden, residual)
        hidden = fwd_out
        residual = some(fwd_res)

      echo "================================================================="
      echo "✓ PASS: All 3 blocks match within tolerance"
      true

when isMainModule:
  main()
