# Tattletale
# Copyright (c) 2026 Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

## Test Qwen3 long residual stream invariant.
##
## Strategy:
## - Load fixtures generated by gen_3_block_long_residual.py
## - For each block, verify the invariant: output + residual == hf_layer_output
## - This proves that the Nim long residual stream implementation is correct.
##
## The invariant is proven in WIP/Spec_Residual_Patterns.md and tested here.

import
  std/memfiles,
  std/strformat,
  std/tables,
  std/os,
  std/options,
  std/importutils,
  workspace/libtorch,
  workspace/safetensors,
  workspace/safetensors/src/safetensors_libtorch,
  workspace/transformers/src/layers,
  workspace/transformers/src/layers/rope {.all.},
  workspace/transformers/src/models/qwen3 {.all.},
  workspace/libtorch_testutils

const
  FixtureDir = currentSourcePath().parentDir() / "fixtures" / "long-residual-3-block"
  ModelPath = currentSourcePath().parentDir() / "hf_models" / "Qwen3-0.6B"

proc loadFixture(layerIdx: int): Table[string, Tensor] =
  ## Load fixture from safetensor file.
  let fixturePath = FixtureDir / &"block-{layerIdx:02d}.safetensor"
  var memFile = memFiles.open(fixturePath, mode = fmRead)
  defer: close(memFile)
  let st = safetensors.load(memFile)
  result = initTable[string, Tensor]()
  for name in st.tensors.keys():
    result[name] = st.getTensorOwned(name, kCPU)

proc main() =
  runTest "Qwen3 long residual stream invariant (3 blocks)":
    proc(): bool =
      const tol = 1e-5

      let model = loadQwen3ModelRaw(ModelPath, kCPU)
      privateAccess(Qwen3Model)

      # Input tokens: "Hello, how are you?"
      let inputIds = @[9707.int64, 11, 1246, 525, 498, 30].toTensor().unsqueeze(0)

      # Embedding pass
      let x = model.embedTokens.forward(inputIds)
      var hidden = x
      var residual: Option[Tensor] = none(Tensor)

      echo "Comparing 3-block long residual stream invariant..."
      echo "================================================================="

      for layerIdx in 0..2:
        let fixture = loadFixture(layerIdx)
        var layer = model.layers[layerIdx]

        # Set RoPE cache from fixture
        let cos = fixture["cos"]
        let sin = fixture["sin"]
        layer.attn.rotary.setCache(cos, sin)

        # Forward through layer (long residual stream pattern)
        let (output, newResidual) = layer.forward(hidden, residual)

        # Compare: Nim (output + residual) vs HF (hf_layer_output)
        # KEY TEST: by the mathematical proof, these sums should be identical
        let nimSum = output + newResidual
        let hfOutput = fixture["hf_layer_output"]
        let diff = (nimSum.to(kFloat32) - hfOutput.to(kFloat32)).abs().max().item(float)

        echo &"Layer {layerIdx:02d}: output + residual diff = {diff:.6e}"

        # Update state
        hidden = output
        residual = some(newResidual)

        # Strict check: must match within BF16 tolerance
        if diff > tol:
          raise newException(ValueError, &"Layer {layerIdx:02d}: output + residual diff = {diff:.6e} exceeds BF16 tolerance")

      echo "================================================================="
      echo "✓ PASS: All 3 blocks match within BF16 tolerance"
      true

when isMainModule:
  main()
