# Tattletale
# Copyright (c) 2026 Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

## nim cpp -r --hints:off --warnings:off --outdir:build/tests/qwen35-greedy \
##   --nimcache:nimcache/tests/qwen35-greedy \
##   workspace/transformers/tests/q_bf16/test_qwen3_5_07_greedy_decoding.nim

import
  std/json,
  std/os,
  std/strutils,
  workspace/libtorch as F,
  workspace/toktoktok,
  workspace/transformers/src/models,
  workspace/transformers/src/samplers,
  workspace/libtorch_testutils

const
  ModelPath = currentSourcePath().parentDir() / ".." / "hf_models" / "Qwen3.5-0.8B"
  FixtureDir = currentSourcePath().parentDir() / ".." / "fixtures" / "greedy-decoding" / "Qwen3.5-0.8B"

# Greedy contract: the fixtures were generated by the vendored model at
# temp 0 from the prompt tokens (decode entry, no bos), stopping at config
# eos 248044. generate() uses the same stop condition and sample() at
# temp 0 is argmax, so the generated ids must match token for token.
# None of the three fixtures reaches eos within num_generated_tokens (8),
# so the eos stop path is not exercised by them.

proc checkFixture(model: Model, jsonPath: string): bool =
  ## Run one greedy fixture and compare the generated ids token-exact.
  ## Returns true on a match, false on divergence (with the first
  ## differing position reported).
  let data = parseJson(readFile(jsonPath))
  var prompt = data["prompt"].getStr()

  # The resume fixture prompt is stored decomposed (e + U+0301). The
  # vendored tokenizer applies the tokenizer.json NFC normalizer before
  # splitting, so it maps the decomposed and precomposed forms to the same
  # ids. toktoktok does not implement the normalizer, so pass the
  # precomposed form, which is the NFC result the vendored tokenizer
  # computes internally. The generated ids below are still compared
  # token-exact against the fixture.
  if jsonPath.endsWith("The_resume_is_ready.json"):
    prompt = "The r\u00e9sum\u00e9 is ready"

  var expectedIds: seq[int] = @[]
  for el in data["generated_ids"]:
    expectedIds.add(el.getInt())

  let expectedText = data["generated_text"].getStr()
  let numPrompt = data["num_prompt_tokens"].getInt()
  let numGen = data["num_generated_tokens"].getInt()

  echo "  Prompt (" & $numPrompt & " tokens): " & prompt

  let output = model.generate(prompt, temp = 0.0f, maxTokens = numGen,
                              maxContextLen = 512)

  # Re-encode the output and slice off the prompt tokens to recover the
  # generated ids.
  let actualIds = model.getTokenizer().encode(output)
  let actualGenerated = if actualIds.len >= numPrompt:
    actualIds[numPrompt ..< actualIds.len]
  else:
    actualIds

  echo "  Expected (" & $expectedIds.len & " tokens): " & expectedText
  echo "  Actual   (" & $actualGenerated.len & " tokens): " &
    model.getTokenizer().decodeToString(actualGenerated)

  if actualGenerated == expectedIds:
    echo "  token ids match"
    return true

  var firstDiff = "n/a"
  for i in 0 ..< min(expectedIds.len, actualGenerated.len):
    if expectedIds[i] != actualGenerated[i]:
      firstDiff = "token " & $i & ": expected " & $expectedIds[i] &
        ", got " & $actualGenerated[i]
      break
  if expectedIds.len != actualGenerated.len:
    firstDiff = "length: expected " & $expectedIds.len & ", got " &
      $actualGenerated.len
  echo "  token ids diverge: " & firstDiff
  false

proc main() =
  runCppTest "Qwen3.5-0.8B greedy decoding - token-exact vs fixtures":
    proc(): bool =
      echo "Loading model..."
      let model = loadModel($(ModelPath), kCPU)
      echo "Model loaded."
      echo ""

      # Greedy must be deterministic argmax: sample() at temp 0 short-
      # circuits to logits.argmax() with no Gumbel noise. Lock it on a
      # fixed logits row so the token-exact comparisons below cannot
      # flake on sampler randomness.
      let fixedLogits = F.toTensor([[1.0f, 2.5f, 0.3f, 4.0f, 3.2f]])
      doAssert sample(fixedLogits, 0.0f) == fixedLogits.argmax().item(int),
        "temp 0 must be deterministic argmax"

      var passed = 0
      var total = 0
      for f in ["Hello_how_are_you.json",
                "The_resume_is_ready.json",
                "What_is_the_capital_of_France.json"]:
        inc total
        echo "Fixture: " & f
        if checkFixture(model, FixtureDir / f):
          inc passed
        echo ""

      echo "Greedy decoding: " & $passed & "/" & $total & " fixtures match"
      result = passed == total

when isMainModule:
  main()
