## Metal 31-binding limit, proven through the printer seam. Both kernels
## below are generated by the `metal:` macro, so the ingest-time check
## scans printer-emitted MSL, not hand-written text.
##
## The default case compiles the 31-binding legal-boundary kernel
## (output at index 0 plus 30 inputs at indices 1..30), binds and reads every input buffer,
## and exits zero.
## The kernel body sums all 30 inputs, so a dropped binding changes the result.
## With `-d:case32` the kernel has 32 buffer bindings (index 31 out of bounds). The engine quits
## at ingest, before newLibraryWithSource runs, with its own limit message on stderr.
## The non-zero exit code and the engine message are the assertions.
##
## Tested ABI (macOS 26.6.1, 2026-08-17): libobjc, Metal.framework, CLT SDK 26.5,
## Nim 2.2.10, MSL 4.0.
##
## Run (default, legal boundary, exit 0):
##   cd tattletale
##   nim c -r --hints:off --warnings:off \
##     --outdir:build/tests --nimcache:nimcache/tests \
##     workspace/crucible/tests/codegen/metal/test_metal_31_bindings.nim
## Run (32-binding ingest quit, exit 1):
##   nim c -r --hints:off --warnings:off -d:case32 \
##     --outdir:build/tests --nimcache:nimcache/tests \
##     workspace/crucible/tests/codegen/metal/test_metal_31_bindings.nim

import workspace/crucible

# The legal boundary: 31 buffer bindings at indices 0..30.
# Metal's limit is exactly 31, so this kernel must compile and dispatch.
const boundaryMsl = metal:
  proc boundary(output: ptr UncheckedArray[uint32];
                a0: ptr UncheckedArray[uint32];
                a1: ptr UncheckedArray[uint32];
                a2: ptr UncheckedArray[uint32];
                a3: ptr UncheckedArray[uint32];
                a4: ptr UncheckedArray[uint32];
                a5: ptr UncheckedArray[uint32];
                a6: ptr UncheckedArray[uint32];
                a7: ptr UncheckedArray[uint32];
                a8: ptr UncheckedArray[uint32];
                a9: ptr UncheckedArray[uint32];
                a10: ptr UncheckedArray[uint32];
                a11: ptr UncheckedArray[uint32];
                a12: ptr UncheckedArray[uint32];
                a13: ptr UncheckedArray[uint32];
                a14: ptr UncheckedArray[uint32];
                a15: ptr UncheckedArray[uint32];
                a16: ptr UncheckedArray[uint32];
                a17: ptr UncheckedArray[uint32];
                a18: ptr UncheckedArray[uint32];
                a19: ptr UncheckedArray[uint32];
                a20: ptr UncheckedArray[uint32];
                a21: ptr UncheckedArray[uint32];
                a22: ptr UncheckedArray[uint32];
                a23: ptr UncheckedArray[uint32];
                a24: ptr UncheckedArray[uint32];
                a25: ptr UncheckedArray[uint32];
                a26: ptr UncheckedArray[uint32];
                a27: ptr UncheckedArray[uint32];
                a28: ptr UncheckedArray[uint32];
                a29: ptr UncheckedArray[uint32]) {.global.} =
    # every input contributes to the sum, so a dropped binding changes the result
    output[0] = a0[0] + a1[0] + a2[0] + a3[0] + a4[0] + a5[0] + a6[0] + a7[0] + a8[0] + a9[0] +
                a10[0] + a11[0] + a12[0] + a13[0] + a14[0] + a15[0] + a16[0] + a17[0] + a18[0] + a19[0] +
                a20[0] + a21[0] + a22[0] + a23[0] + a24[0] + a25[0] + a26[0] + a27[0] + a28[0] + a29[0]

# One past the limit: 32 buffer bindings, index 31 out of bounds.
# The engine must quit at ingest with its own message, before the Metal compiler
# gets a chance to reject the same source.
const tooManyMsl = metal:
  proc tooMany(output: ptr UncheckedArray[uint32];
               a0: ptr UncheckedArray[uint32];
               a1: ptr UncheckedArray[uint32];
               a2: ptr UncheckedArray[uint32];
               a3: ptr UncheckedArray[uint32];
               a4: ptr UncheckedArray[uint32];
               a5: ptr UncheckedArray[uint32];
               a6: ptr UncheckedArray[uint32];
               a7: ptr UncheckedArray[uint32];
               a8: ptr UncheckedArray[uint32];
               a9: ptr UncheckedArray[uint32];
               a10: ptr UncheckedArray[uint32];
               a11: ptr UncheckedArray[uint32];
               a12: ptr UncheckedArray[uint32];
               a13: ptr UncheckedArray[uint32];
               a14: ptr UncheckedArray[uint32];
               a15: ptr UncheckedArray[uint32];
               a16: ptr UncheckedArray[uint32];
               a17: ptr UncheckedArray[uint32];
               a18: ptr UncheckedArray[uint32];
               a19: ptr UncheckedArray[uint32];
               a20: ptr UncheckedArray[uint32];
               a21: ptr UncheckedArray[uint32];
               a22: ptr UncheckedArray[uint32];
               a23: ptr UncheckedArray[uint32];
               a24: ptr UncheckedArray[uint32];
               a25: ptr UncheckedArray[uint32];
               a26: ptr UncheckedArray[uint32];
               a27: ptr UncheckedArray[uint32];
               a28: ptr UncheckedArray[uint32];
               a29: ptr UncheckedArray[uint32];
               a30: ptr UncheckedArray[uint32]) {.global.} =
    output[0] = 1'u32

proc runTest() =   # private: the -d: define selects the case and engines are destroyed at return
  when defined(case32):
    # A 32-buffer kernel must quit at ingest, before Metal's own compile error appears.
    var engine = bkMetal.init()
    engine.ingest(tooManyMsl)
    echo "UNEXPECTED: ingest succeeded with 32 buffers"
  else:
    # The 31-binding legal boundary: the ingest check passes, and Metal
    # compiles the printer-emitted kernel. The dispatch then succeeds.
    var engine = bkMetal.init()
    engine.ingest(boundaryMsl)
    var res: array[1, uint32]
    var in0 = [1'u32]
    var in1 = [2'u32]
    var in2 = [3'u32]
    var in3 = [4'u32]
    var in4 = [5'u32]
    var in5 = [6'u32]
    var in6 = [7'u32]
    var in7 = [8'u32]
    var in8 = [9'u32]
    var in9 = [10'u32]
    var in10 = [11'u32]
    var in11 = [12'u32]
    var in12 = [13'u32]
    var in13 = [14'u32]
    var in14 = [15'u32]
    var in15 = [16'u32]
    var in16 = [17'u32]
    var in17 = [18'u32]
    var in18 = [19'u32]
    var in19 = [20'u32]
    var in20 = [21'u32]
    var in21 = [22'u32]
    var in22 = [23'u32]
    var in23 = [24'u32]
    var in24 = [25'u32]
    var in25 = [26'u32]
    var in26 = [27'u32]
    var in27 = [28'u32]
    var in28 = [29'u32]
    var in29 = [30'u32]
    engine.run("boundary", res,
               (in0, in1, in2, in3, in4, in5, in6, in7, in8, in9,
                in10, in11, in12, in13, in14, in15, in16, in17, in18, in19,
                in20, in21, in22, in23, in24, in25, in26, in27, in28, in29))
    if res[0] != 465'u32:
      stderr.write("UNEXPECTED: boundary kernel returned " & $res[0] & ", expected 465\n")
      quit 1
    echo "OK: 31-binding macro-generated kernel compiled and dispatched"

when isMainModule:
  runTest()
