# Tattletale
# Copyright (c) 2026 Mamy André-Ratsimbazafy
# Licensed under MIT or Apache v2
#
# STANDALONE REPRODUCTION: Tensor shape corruption bug with RMSnorm
#
# NO dependencies on transformers package - uses only safetensors fixtures.

import
  std/memfiles,
  std/options,
  std/os,
  std/strformat,
  std/strutils,
  std/tables,
  workspace/libtorch as F,
  workspace/libtorch_testutils,
  workspace/safetensors

const
  # Standalone fixtures generated by testgen/gen_aliasing_fixtures.py
  FixtureDir = currentSourcePath().parentDir() / "testgen" / "fixtures" / "aliasing"
  ModelPath = FixtureDir / "model.safetensor"

proc main() =
  runTest "Tensor shape corruption bug":
    proc(): bool =
      echo "=== TENSOR SHAPE CORRUPTION BUG ==="
      echo ""
      echo "ROOT CAUSE: Loading a new safetensors file corrupts"
      echo "            the shape of previously loaded tensors."
      echo ""
      echo "This happens DURING getTensorOwned, NOT during layer init."
      echo ""

      # Step 1: Load weights ONCE from model file
      echo "Step 1: Load weights from model.safetensor (once)..."
      var weightsMemFile = memFiles.open(ModelPath, mode = fmRead)
      defer: close(weightsMemFile)

      var weightsSt = safetensors.load(weightsMemFile)
      let inputLnWeight = weightsSt.getTensorOwned("input_layernorm.weight")
      let postAttnWeight = weightsSt.getTensorOwned("post_attention_layernorm.weight")

      echo "  inputLnWeight.shape = ", inputLnWeight.shape
      echo "  postAttnWeight.shape = ", postAttnWeight.shape
      echo "  Expected: both [64]"
      echo ""

      # Step 2: Load fixture files - this is where corruption happens
      echo "Step 2: Load fixture files (corruption happens here)..."
      echo ""

      for caseNum in 0..3:
        let fixturePath = FixtureDir / fmt"norm-{caseNum:02d}.safetensor"
        if not fileExists(fixturePath):
          echo "  Skipping case ", caseNum, " (file not found)"
          continue

        echo "--- Case ", caseNum, " ---"
        echo "  Before loading fixture:"
        echo "    inputLnWeight.shape = ", inputLnWeight.shape
        echo "    postAttnWeight.shape = ", postAttnWeight.shape

        # Load fixture - THIS IS WHERE CORRUPTION HAPPENS
        var fixtureMemFile = memFiles.open(fixturePath, mode = fmRead)
        defer: close(fixtureMemFile)

        var st = safetensors.load(fixtureMemFile)
        let inputHiddenStates = st.getTensorOwned("input_hidden_states")
        let layerPath = st.metadata.unsafeGet().getOrDefault("layer", "")

        echo "  After loading fixture:"
        echo "    inputLnWeight.shape = ", inputLnWeight.shape
        echo "    postAttnWeight.shape = ", postAttnWeight.shape
        echo "    inputHiddenStates.shape = ", inputHiddenStates.shape
        echo "    layerPath = ", layerPath

        # Check if shapes changed
        let inputLnShape = @(inputLnWeight.shape)
        let postAttnShape = @(postAttnWeight.shape)

        if inputLnShape != @[64] or postAttnShape != @[64]:
          echo ""
          echo "❌ BUG: Weight shapes corrupted!"
          echo "   Expected: both [64]"
          echo "   Got:      inputLn=", inputLnShape, ", postAttn=", postAttnShape
          echo ""
          return false
        echo ""

      echo "=== Test passed - no corruption detected ==="
      echo ""
      true

when isMainModule:
  main()