# Tattletale
# Copyright (c) 2026 Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

## PROVENANCE.md generation and verification.
##
## Every fixture recording writes the recording environment
## as key-value rows in PROVENANCE.md, rendered deterministically.
## The verifier re-renders the file from parsed entries and compares
## bytes. The recording environment tracks upstream. Versions are
## written as rows, never locked in a lockfile.

import
  std/os,
  std/algorithm,
  std/strutils,
  std/sets

type ProvenanceEntry* = tuple[key, value: string]

const RequiredProvenanceKeys* = [
  "python",
  "torch",
  "transformers",
  "recorded_from",
]
  ## Keys every PROVENANCE.md must carry. recorded_from names the box
  ## plus backend the recording ran on, e.g. "m4max-cpu".

proc renderProvenance*(entries: seq[ProvenanceEntry]): string =
  ## Deterministic markdown rendering: a title line, a contract note,
  ## then one `| key | value |` row per entry in sorted key order.
  let sorted = entries.sorted(proc(a, b: ProvenanceEntry): int = cmp(a.key, b.key))
  result = "# PROVENANCE\n\n"
  result.add "Recording environment rows. Generated by harness/provenance.nim, never hand-edited.\n\n"
  result.add "| key | value |\n"
  result.add "|-----|-------|\n"
  for (key, value) in sorted:
    result.add "| " & key & " | " & value & " |\n"

proc writeProvenance*(path: string, entries: seq[ProvenanceEntry]) =
  ## Render the rows and write them to `path`.
  writeFile(path, renderProvenance(entries))

proc parseProvenance*(text: string): seq[ProvenanceEntry] =
  ## Parse the `| key | value |` rows of a rendered PROVENANCE.md.
  ## Raises ValueError on a malformed row.
  for line in text.splitLines():
    let trimmed = line.strip()
    if not trimmed.startsWith("|"):
      continue
    let cells = trimmed.split("|")
    if cells.len != 4:
      raise newException(ValueError, "malformed provenance row: " & trimmed)
    let key = cells[1].strip()
    let value = cells[2].strip()
    if key == "key":
      continue
    # The markdown separator row is table furniture, not an entry.
    # Parsing it back as a key-value row would sort the separator ahead
    # of the rendered rows and break the byte-level re-render.
    if key.allCharsInSet({'-'}):
      continue
    result.add ((key, value))

proc verifyProvenance*(path: string): bool =
  ## Byte-level verification: parse the file, re-render, compare. Also
  ## requires every key in RequiredProvenanceKeys to be present. Raises
  ## ValueError on malformed content, returns false on any mismatch.
  let text = readFile(path)
  let entries = parseProvenance(text)
  if renderProvenance(entries) != text:
    return false
  var present = initHashSet[string]()
  for (key, _) in entries:
    present.incl(key)
  for required in RequiredProvenanceKeys:
    if required notin present:
      return false
  result = true
