#!/usr/bin/env python3
"""
Generate fixture files for tokenizer testing via HuggingFace tokenizers library.

This generates fixtures using the HuggingFace tokenizers library directly,
which should produce identical results to our Nim HF-to-tiktoken conversion.

Fixtures are JSON files with the format:
{
    "text": "Some example text",
    "token_ids": [10, 234, 6909, ..., 99],
    "tokenizer": "gpt2-tokenizer.json"
}
"""

import json

from zstd_frame import write_text_zst
from pathlib import Path
from typing import Dict, List, Any
from tokenizers import Tokenizer

TEST_DIR = Path(__file__).parent.resolve()
TOKENIZERS_DIR = TEST_DIR / "tokenizers"
FIXTURES_DIR = TEST_DIR / "fixtures" / "small"
FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

HF_FILES = {
    "gpt2": "gpt2-tokenizer.json",
    "llama3": "llama3-tokenizer.json",
    "minimax-m2.1": "minimax-m2.1-tokenizer.json",
    "glm-4.7": "glm-4.7-tokenizer.json",
    "exaone": "exaone-tokenizer.json",
    "step-3.5-flash": "step-3.5-flash-tokenizer.json",
}


def generate_fixture(
    text: str, tokenizer_name: str, tokenizer: Tokenizer
) -> Dict[str, Any]:
    """Generate a single fixture entry."""
    encoding = tokenizer.encode(text, add_special_tokens=False)
    return {"text": text, "token_ids": encoding.ids, "tokenizer": tokenizer_name}


def get_test_texts() -> List[tuple[str, str]]:
    """Get all test texts for fixture generation."""
    texts = []

    # From gen_fixtures_via_tiktoken.py
    texts.extend(
        [
            ("chinese", "你好世界"),
            ("japanese", "こんにちは"),
            ("korean", "안녕하세요 세계"),
            ("russian", "Привет мир"),
            ("hebrew", "שלום עולם"),
            ("khmer", "សួស្តីពិភពលោក"),
            ("emoji", "Hello 🌍 World! 🎉"),
            ("mixed_cjk", "Hello 世界 こんにちは 안녕"),
            ("hello_world", "Hello, world!"),
        ]
    )

    # Greek texts
    texts.extend(
        [
            ("greek_basic", "Ελληνικά και μαθηματικά"),
            (
                "greek_alphabet",
                "Α α Β β Γ γ Δ δ Ε ε Ζ ζ Η η Θ θ Ι ι Κ κ Λ λ Μ μ Ν ν Ξ ξ Ο ο Π π Ρ ρ Σ σ Τ τ Υ υ Φ φ Χ χ Ψ ψ Ω ω",
            ),
        ]
    )

    # Mathematical symbols (ECC documentation excerpts)
    texts.extend(
        [
            ("ecc_endo", "Check the Endomorphism for p mod 3 == 1"),
            (
                "ecc_cube_roots",
                "x³−1=0 <=> (x−1)(x²+x+1) = 0, if x != 1, x solves (x²+x+1) = 0 <=> x = (-1±√3)/2",
            ),
            (
                "ecc_curve",
                "y² = x³ + b, and y² = (x𝜑)³ + b <=> y² = x³ + b (with 𝜑³ == 1) so we are still on the curve",
            ),
            ("ecc_lambda", "λᵩ² + λᵩ + 1 ≡ 0 (mod r) and 𝜑² + 𝜑 + 1 ≡ 0 (mod p)"),
            ("ecc_scalar", "[a]P to represent P+P+ .... + P"),
            (
                "ecc_bilinear",
                "e: 𝔾1 x 𝔾2 -> 𝔾t that map is bilinear e([a]P, [b]Q) = e(P, Q)ᵃᵇ",
            ),
            (
                "ecc_srs",
                "srs_g1: [[1]₁, [τ]₁, [τ²]₁, ... [τⁿ⁻¹]₁] also called powers of tau",
            ),
            (
                "ecc_commitment",
                "commit(srs_g1, blob) -> commitment C = ∑ blobᵢ.srs_g1ᵢ = ∑ [blobᵢ.τⁱ]₁ = [p(τ)]₁",
            ),
            ("ecc_witness", "w(x, z) = (p(x) - p(z)) / (x-z)"),
            ("ecc_verification", "e([proof]₁, [τ]₂ - [z]₂) = e(C - [y]₁, [1]₂)"),
            ("ecc_lagrange", "ω ∈ 𝔽r a root of unity of order n, i.e. ωⁿ = 1"),
        ]
    )

    # Group theory refresher
    texts.extend(
        [
            (
                "group_basics",
                "A group is a set of elements with a binary operation called the group law with a neutral element and an inverse.",
            ),
            (
                "field_basics",
                "A field is a set of elements with two group laws, addition and multiplication, with corresponding inverse properties.",
            ),
            ("finite_field", "𝔽r is a finite-field of prime order r"),
            (
                "cyclic_group",
                "The group can be cyclic, i.e. all elements of the group can be generated by repeatedly applying the group law.",
            ),
            (
                "additive_notation",
                "[a]P to represent P+P+ .... + P, applying the group law a times, i.e. the scalar multiplication.",
            ),
        ]
    )

    # Polynomial commitment scheme
    texts.extend(
        [
            (
                "pcs_prover",
                "Prover computes witness polynomial w(x, z) = (p(x) - p(z)) / (x-z)",
            ),
            (
                "pcs_verifier",
                "Verifier checks proof.(τ-z) = p(τ) - y using bilinear pairing",
            ),
            (
                "pcs_fiat_shamir",
                "To make the protocol non-interactive, z may be computed via the Fiat-Shamir heuristic.",
            ),
            (
                "pcs_schwartz",
                "According to the Schwartz-zippel Lemma it is cryptographically unlikely that this equation holds",
            ),
            (
                "pcs_srs_g1",
                "srs_g1: [[1]₁, [τ]₁, [τ²]₁, ... [τⁿ⁻¹]₁] also called powers of tau, with a bounded degree n-1",
            ),
            ("pcs_srs_g2", "srs_g2: [[1]₂, [τ]₂]"),
            (
                "pcs_trust_setup",
                "τ and its powers are secrets that no one knows, we only work with [τⁱ]₁ and [τ]₂ not with τ directly",
            ),
            ("pcs_monomial", "p(x) = blob₀ + blob₁ x + blob₂ x² + ... + blobₙ₋₁ xⁿ⁻¹"),
        ]
    )

    # Chinese historical text with Chinese punctuation - regression test for KimiK2.5
    texts.extend(
        [
            (
                "sanguozhi_paragraph",
                "紅。白\n髮漁樵江渚上，慣看秋月春風。一壺濁酒喜相逢：古今多少事，都付笑談中。\n\n　　話說天下大勢，分久必合，合久必分：周末七國分爭，并入於秦。及秦滅之後，楚\n、漢分爭，又并入於漢。漢朝自高祖斬白蛇而起義，一統天下。後來光武中興，傳至獻\n帝遂分為三國。推其致亂之由，殆始於桓、靈二帝。桓帝禁錮善類，崇信宦官。及桓\n帝崩，靈帝即位，大將軍竇武",
            ),
        ]
    )

    return texts


def generate_hf_fixtures():
    """Generate fixtures for HF tokenizers using the tokenizers library."""
    for hf_name, hf_filename in HF_FILES.items():
        hf_path = TOKENIZERS_DIR / hf_filename
        if not hf_path.exists():
            print(f"[SKIP] {hf_path} not found")
            continue

        print(f"Processing HF {hf_name}...")
        tokenizer = Tokenizer.from_file(str(hf_path))

        fixtures = []
        for name, text in get_test_texts():
            fixture = generate_fixture(text, hf_filename, tokenizer)
            fixtures.append({"name": name, **fixture})

        output_path = FIXTURES_DIR / f"hf_{hf_name}.json.zst"
        write_text_zst(output_path,
                       json.dumps(fixtures, ensure_ascii=False,
                                  indent=2).encode("utf-8"))
        print(f"  [OK] Generated {len(fixtures)} fixtures to {output_path}")


def main():
    """Generate all fixtures."""
    print("=" * 70)
    print("Generating tokenizer fixtures via HuggingFace tokenizers")
    print("=" * 70)

    generate_hf_fixtures()

    print("=" * 70)
    print("Fixture generation complete")
    print("=" * 70)


if __name__ == "__main__":
    main()
